### ISSUE TITLE
Delay 😢

### ISSUE THREAD

**Issue by jbobrow** [confus-3d/Simon#1]
Blinks can't play nicely with `delay()` since the BlinkOS runs constantly to keep Blinks in communication with one another. Instead, try using the `Timer` 👍

**Comment by confus-3d** [comment]
I just used delay because i readed this into the keywords.txt in Blinks-SDK:

//# <avr/delay.h> - http://www.nongnu.org/avr-libc/user-manual/group__util__delay.html
_delay_ms	KEYWORD2
_delay_us	        KEYWORD2

What do you think about using this for a ´delay(200)´:

int flag = 0;
Timer waitingTimer = 200
    while(flag == 0){
        if (waitingTimer.isExpired()) {
          flag = 1;
        }
    }

I just want it to stop reading the next lines of code for 200ms

**Comment by confus-3d** [comment]
Changed all delay(200) for waitingTimer.set(200) && while
